#!/bin/bash

# Firewall 
ufw enable

# Monitors & Workspaces
~/.config/bspwm/scripts/monitor_workspaces.sh &

# Wallpaper
nitrogen --restore

# BSPWM Configuration
bspc config border_width         2
bspc config window_gap           0
bspc config split_ratio          0.52
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config top_padding 0

# Rules
# You can get the window name using the following command: xprop | grep WM_CLASS
bspc rule -a flameshot state='floating'
bspc rule -a *:SPLASH state=floating
bspc rule -a BoltLauncher desktop=^8 state=floating
bspc rule -a steam_app_1284210 desktop=^2
bspc rule -a net-runelite-client-RuneLite desktop=^1
bspc rule -a steam desktop=^7
bspc rule -a discord desktop=^6
bspc desktop -f 1

# Run polkit daemon if doesn't started.
[ -n "$(pidof xfce-polkit)" ] || /usr/lib/xfce-polkit/xfce-polkit &

# Polybar
~/.config/bspwm/scripts/launch_polybar.sh

# Daemons
command -v sxhkd >/dev/null && pkill -x sxhkd; sleep 1; sxhkd &
command -v picom >/dev/null && pkill -x picom; sleep 1; picom &
command -v dunst >/dev/null && pkill -x dunst; sleep 1; dunst &

# Keyboard
setxkbmap -layout us -variant intl -option "compose:c,compose:menu,lv3:ralt_switch"

# Mouse/Cursor
xsetroot -cursor_name left_ptr &

# Color temperature
CONTENT=$(curl -s https://freegeoip.app/json/) 
longitude=$(echo $CONTENT | jq .longitude)
latitude=$(echo $CONTENT | jq .latitude)
command -v redshift >/dev/null && pkill -x redshift; sleep 1; redshift -l $latitude:$longitude &
